meta:
  version: 1
  hydromt_version: ">=0.10"
  root: C:/Users/vaspapa/Desktop/ELKAK/implementation/pineios_sfincs/data

copdem30:
  data_type: RasterDataset
  driver: raster
  path: copdem30/copdem30.vrt
  crs: 4326
  meta:
    category: topography
    source_url: https://copernicus-dem-30m.s3.amazonaws.com
    source_version: GLO-30 (2021)
  rename:
    Band1: elevtn
    band_1: elevtn

esa_worldcover_2021:
  data_type: RasterDataset
  driver: raster
  path: esa_worldcover/ESA_WorldCover_10m_2021_v200_N39E021_Map.tif
  crs: 4326
  meta:
    category: landuse
    source_url: https://esa-worldcover.s3.amazonaws.com
    source_version: v200 (2021)
  rename:
    Band1: landuse
    band_1: landuse

era5_hourly:
  data_type: RasterDataset
  driver: netcdf
  path: era5_pineios.nc
  crs: 4326
  meta:
    category: meteo
    source_version: ERA5-single-levels reanalysis (Sept 1-9 2023, 0.25 deg)

glofas_v4_daily:
  data_type: RasterDataset
  driver: netcdf
  path: glofas_pineios.nc
  crs: 4326
  meta:
    category: hydrography
    source_version: GloFAS v4.0 historical reanalysis (Aug-Sept 2023, 0.05 deg)
